### ISSUE TITLE
How to make it work on a project with different folder?

### ISSUE THREAD

**Issue by josinaldobarbosa** [vladimirpetrovski/bitrise-step-version-extractor-android#3]
My android project is inside the android folder:
- my-project
  - android
  - other folders...

in the step I configured it this way:
```
- version-extractor-android@0:
        inputs:
        - variant: "$VARIANT"
        - gradlew_path: ./android/gradlew
        - build_gradle_path: "./android/app/build.gradle"
```
But I get this error:
```
FAILURE: Build failed with an exception.

* What went wrong:
Task 'printVersionRelease' not found in root project 'my-project'.

* Try:
Run gradlew tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 537ms
```

To solve quickly I changed gradlew_path to `gradlew_path: cd android && ./gradlew`
